[project]
authors = ["Howard Nguyen-Huu <howardnguyenhuu@gmail.com>"]
channels = ["conda-forge"]
description = "experimenting with controllers for physics-simulated humanoids"
name = "humanoid"
platforms = ["linux-64"]
version = "0.0.1"

[system-requirements]
cuda = "12.1"

[dependencies]
python = "3.8.*"

[pypi-dependencies]
isaacgym = { path = "packages/isaacgym/python", editable = true }
jupyterlab = "*"
matplotlib = "*"
protobuf = "*"
ray = "*"
rl-games = { path = "packages/rl_games", editable = true }
ruff = "*"
tensorboard = "*"
termcolor = "*"
torch = "*"
torchvision = "*"

[pypi-options]
extra-index-urls = [ "https://download.pytorch.org/whl/cu124" ]

[tasks]
slint = "python -m ruff check"
lint = "python -m ruff format"
check-torch = { cmd = "python check_torch.py --cuda", cwd = "scripts" }
joint-monkey = { cmd = "python joint_monkey.py", cwd = "packages/isaacgym/python/examples" }
skillmimic = { cmd = "python skillmimic/run.py", cwd = "projects" }
