[project]
name = "puffer-advantage"
description = ""
# authors = [
#     { name = "", email = "" },
# ]
requires-python = ">=3.8"
version = "0.1.0"
dependencies = [
    "torch",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["puffer_advantage"]
