[project]
description = "WorldPoseDataset Visualization: https://github.com/eth-ait/WorldPoseDataset/tree/visualization"
name = "world_pose_viewer"
requires-python = ">=3.8"
version = "0.1.0"
dependencies = [
   "numpy",
   "aitviewer",
   "opencv-python",
   "torch",
   "tqdm",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["world_pose_viewer"]
