[project]
description = "Simplified Perceptual Humanoid Control with Pufferlib"
name = "puffer-phc"
authors = [
    { name = "Kyoung Whan Choe", email = "choe.kyoung@gmail.com" },
]
requires-python = ">=3.8,<3.9"
version = "0.1.0"
dependencies = [
    "wandb>=0.16.6,<0.17",
    "tyro>=0.8.14,<0.9",
    "polars>=1.5.0,<2",
    "joblib>=1.4.2,<2",
    "torch==2.3.1",
    "torchvision>=0.18.1,<0.19",
    "scipy>=1.10.1,<2",
    "imageio",
    "fsspec>=2024.10.0,<2025",
    "debugpy>=1.8.5,<2",

    "isaacgym",

    "pufferlib@git+https://github.com/kywch/PufferLib.git",
    "smpl_sim@git+https://github.com/kywch/SMPLSim.git",
    "chumpy@git+https://github.com/nico-von-huene/chumpy.git",
    "carbs@git+https://github.com/PufferAI/carbs.git",    
]

[build-system]
requires = ["Cython>=3.0", "pip>=23.0", "hatchling", "wheel", "numpy==1.23.3"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["puffer_phc"]

[tool.hatch.metadata]
allow-direct-references = true
